/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example user1 */
                        username: string;
                        /** @example user1@example.com */
                        email: string;
                        /** @example password123 */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description User created successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login a user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example user1 */
                        username: string;
                        /** @example password123 */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description Login successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch protected data */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/weather": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current weather for a location
         * @description Retrieves current weather data using the Open-Meteo API. Requires `latitude` and `longitude` query parameters.
         */
        get: {
            parameters: {
                query: {
                    latitude: number;
                    longitude: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Returns current weather data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            location: {
                                /** @example 52.52 */
                                latitude: number;
                                /** @example 13.41 */
                                longitude: number;
                                /** @example Europe/Berlin */
                                timezone: string;
                            };
                            current: {
                                /**
                                 * Format: date-time
                                 * @example 2025-12-02T12:00:00Z
                                 */
                                time: string;
                                temperature: {
                                    /** @example 5.4 */
                                    value: number;
                                    /** @example °C */
                                    unit: string;
                                };
                                apparentTemperature: {
                                    /** @example 3.2 */
                                    value: number;
                                    /** @example °C */
                                    unit: string;
                                };
                                humidity: {
                                    /** @example 85 */
                                    value: number;
                                    /** @example % */
                                    unit: string;
                                };
                                precipitation: {
                                    /** @example 0 */
                                    value: number;
                                    /** @example mm */
                                    unit: string;
                                };
                                /** @example 1 */
                                weatherCode: number;
                                wind: {
                                    speed: {
                                        /** @example 3.5 */
                                        value: number;
                                        /** @example km/h */
                                        unit: string;
                                    };
                                    direction: {
                                        /** @example 180 */
                                        value: number;
                                        /** @example ° */
                                        unit: string;
                                    };
                                };
                            };
                        };
                    };
                };
                /** @description Invalid or missing latitude/longitude */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Latitude and longitude are required */
                            message?: string;
                        };
                    };
                };
                /** @description Failed to fetch weather data */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Failed to fetch weather data */
                            message?: string;
                            /** @example Network error */
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/exchange": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get EUR to USD exchange rates for a date range
         * @description Returns historical EUR to USD exchange rates between `startDate` and `endDate`. Useful for charting purposes.
         */
        get: {
            parameters: {
                query: {
                    /** @description Start date of the range (YYYY-MM-DD) */
                    startDate: string;
                    /** @description End date of the range (YYYY-MM-DD) */
                    endDate: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Historical exchange rates */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @example EUR */
                            base: string;
                            /**
                             * Format: date
                             * @example 2025-11-25
                             */
                            startDate: string;
                            /**
                             * Format: date
                             * @example 2025-12-01
                             */
                            endDate: string;
                            rates: {
                                /**
                                 * Format: date
                                 * @example 2025-11-25
                                 */
                                date: string;
                                /** @example 1.082 */
                                rate: number;
                            }[];
                        };
                    };
                };
                /** @description Missing or invalid query parameters */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example startDate and endDate query parameters are required */
                            message?: string;
                        };
                    };
                };
                /** @description Failed to fetch exchange rates */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Failed to fetch exchange rates */
                            message?: string;
                            /** @example Network error */
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/flight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current flight data by flight number
         * @description Fetches live flight data using OpenSky Network API (no API key needed)
         */
        get: {
            parameters: {
                query: {
                    flightNumber: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Flight data returned */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            flights: {
                                /** @example 3c6444 */
                                icao24: string;
                                /** @example LH1234 */
                                callsign: string;
                                /** @example Germany */
                                origin_country: string;
                                /** @example 1672531200 */
                                time_position: number;
                                /** @example 1672531210 */
                                last_contact: number;
                                /** @example 13.404 */
                                longitude: number;
                                /** @example 52.52 */
                                latitude: number;
                                /** @example 11000 */
                                baro_altitude: number;
                                /** @example false */
                                on_ground: boolean;
                                /** @example 230 */
                                velocity: number;
                                /** @example 90 */
                                true_track: number;
                                /** @example 5 */
                                vertical_rate: number;
                            }[];
                        };
                    };
                };
                /** @description Missing flightNumber */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Flight not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Failed to fetch flight data */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/data/random-flight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a random current flight
         * @description Fetches a single random flight from the OpenSky Network API (no API key needed)
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Random flight data returned */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            flight: {
                                /** @example 3c6444 */
                                icao24: string;
                                /** @example LH1234 */
                                callsign: string;
                                /** @example Germany */
                                origin_country: string;
                                /** @example 1672531200 */
                                time_position: number;
                                /** @example 1672531210 */
                                last_contact: number;
                                /** @example 13.404 */
                                longitude: number;
                                /** @example 52.52 */
                                latitude: number;
                                /** @example 11000 */
                                baro_altitude: number;
                                /** @example false */
                                on_ground: boolean;
                                /** @example 230 */
                                velocity: number;
                                /** @example 90 */
                                true_track: number;
                                /** @example 5 */
                                vertical_rate: number;
                            };
                        };
                    };
                };
                /** @description No flights available */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example No flights currently available */
                            message?: string;
                        };
                    };
                };
                /** @description Failed to fetch flight data */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example false */
                            success?: boolean;
                            /** @example Failed to fetch flight data */
                            message?: string;
                            /** @example Network error */
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh access token
         * @description Generates a new access token and rotates the refresh token. Requires a valid (non-expired) refresh token in the request body.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description New access and refresh tokens generated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example newAccessTokenHere */
                            accessToken: string;
                            /** @example newRefreshTokenHere */
                            refreshToken: string;
                        };
                    };
                };
                /** @description Invalid or expired refresh token */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Refresh token expired. Please log in again. */
                            message?: string;
                        };
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example Internal server error */
                            message?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
