import { JSX } from "react";
import {
  TiWeatherCloudy,
  TiWeatherDownpour,
  TiWeatherPartlySunny,
  TiWeatherShower,
  TiWeatherSnow,
  TiWeatherStormy,
  TiWeatherSunny,
} from "react-icons/ti";

export const weatherIcons: Record<number, JSX.Element> = {
  0: <TiWeatherSunny />,
  1: <TiWeatherPartlySunny />,
  2: <TiWeatherPartlySunny />,
  3: <TiWeatherCloudy />,
  45: <TiWeatherCloudy />,
  48: <TiWeatherCloudy />,
  51: <TiWeatherShower />,
  53: <TiWeatherShower />,
  55: <TiWeatherShower />,
  56: <TiWeatherShower />,
  57: <TiWeatherShower />,
  61: <TiWeatherDownpour />,
  63: <TiWeatherDownpour />,
  65: <TiWeatherDownpour />,
  66: <TiWeatherDownpour />,
  67: <TiWeatherDownpour />,
  71: <TiWeatherSnow />,
  73: <TiWeatherSnow />,
  75: <TiWeatherSnow />,
  77: <TiWeatherSnow />,
  80: <TiWeatherShower />,
  81: <TiWeatherShower />,
  82: <TiWeatherShower />,
  85: <TiWeatherSnow />,
  86: <TiWeatherSnow />,
  95: <TiWeatherStormy />,
  96: <TiWeatherStormy />,
  99: <TiWeatherStormy />,
};
